name: AgroValle Connect CI

on:
  push:
    branches: [ "main", "develop", "feature/*" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-verify:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo fuente
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 1. Compilar proyecto
        run: ./mvnw clean compile

      - name: 2. Verificar estilo con Checkstyle
        run: ./mvnw checkstyle:check

      - name: 3. Ejecutar pruebas y verificar Cobertura JaCoCo (>= 60%)
        run: ./mvnw test jacoco:check
